---
editor: visual
---

```{r}
#| label: set-up-methods
#| echo: false
library(targets)
library(tarchetypes)

```

## Methods

### Study Sites

The experiment was conducted at twelve semi-natural grassland sites in the Vestland Climate Grid (VCG) in south-western Norway. The sites were selected along three temperature (boreal, sub-alpine, and alpine) and four precipitation levels. The gradients ranged from 6.5째C to 10.5째C growing season temperatures and mean annual precipitation varying from 600 mm to 2600 mm. Apart from differing in mean growing season temperature and annual precipitation, the sites were selected to be as similar as possible in grazing regime and history, bedrock, vegetation type and structure, slope and exposure. For more details on the study site and experimental design see @vandvik2022role.

### Experimental Design

To assess the effects of plant functional group removals on standing biomass and community composition, we set up a fully factorial plant functional group removal experiment in 2015. We focused on the dominant plant functional groups including graminoids (G; grasses, sedges, and rushes), forbs (F; including herbaceous forbs, pteridophytes, dwarf-shrubs, and small individuals of trees and shrubs), and bryophytes (B; including mosses, liverworts, and hornworts). At each site, eight 25 x 25 cm plots were established and replicated four times (32 plots per site and n = 384 plots in total). Within each block we randomly assigned the removal treatments of the three plant functional groups and all possible combination resulting in eight treatments: control (intact vegetation), three single functional group removals, three pairwise removals, and complete removal of all three functional groups (bare ground; Figure).

The removals were done annually at peak growing season between 2015 and 2022. In 2016 and 2017, the removals were done twice, including a removal in the spring. The above ground biomass of the relevant plant functional group(s) were removed. The below ground biomass, litter and lichens were left intact.

### Data Collection

#### Above ground biomass (removed and remaining)

Above ground biomass was collected annually from all experimental plots. The biomass was harvested for each plot, separating each functional group (graminoids, forbs, bryophytes), drying it to constant mass at 60째C and weighing.

In 2022, the whole experiment was harvested and the above ground biomass from all plant functional groups in all plots was removed. The biomass was also dried at 60째C and weighed. The biomass from the plant functional groups from the removal treatments is hereafter called *removed biomass*. And the biomass from the remaining plant functional groups is hereafter called *standing biomass*.

#### Plant Community Composition

Plant community composition recorded annually between 2015 and 2019 across all experimental plots. We recorded the presence and visually estimated the cover of each species per plot.

### Data preparation

**Biomass standardisation:** For both biomass harvests in 2015 and in 2022, biomass was standardised to the site level for each functional group removed in each treatment plot. To standardise the biomass removed in 2015, we subtracted the biomass of each functional group in each treatment plot from the mean functional group biomass in the full removal treatment plots at each site. We conducted a similar standardisation for the remaining biomass of the focal functional groups in 2022, instead using the mean site-level biomass of the control plots.

### Analysis

-   Calculate cumulative removed biomass per treatment and functional group

-   Calculate diversity indices

-   Part 1: run models across all data. Test how the number of removed functional groups, identity of removed groups, or cumulative removed biomass of each functional group affected standing biomass. We ran lmer with standing biomass as response and fg, plus temperature and precipitation as predictors. Site was used as random effect. Temperature and precipitation were scaled.

-   We ran the same analysis for each functional group separate (e.g. plots were graminoids present, FB, B, none)

-   Something with diversity
