---
title: "Model Assumption Checking"
format: html
---

## Model Assumption Checking

```{r}
#| label: set-up-si
#| echo: false
#| message: false
# Load required libraries
library(targets)
library(tarchetypes)
library(performance)
```


# Check model diagnostics

## Part 1: General effect of removed biomass on remaining biomass

### Functional group richness
```{r}
#| label: fig-fg-richness-diagnostics
#| echo: false
#| message: false
#| fig-height: 12


# Load the fg_richness_analysis target
tar_load(fg_richness_analysis)

# Check model diagnostics for the 2-way model
result <- check_model_diagnostics(fg_richness_analysis$model_2way)
result  # This will plot the diagnostics
```

### Functional group identity
```{r}
#| label: fig-fg-identity-diagnostics
#| echo: false
#| message: false
#| fig-height: 12

# Load the fg_identity_analysis target
tar_load(fg_identity_analysis)

# Check model diagnostics for the 2-way model
result <- check_model_diagnostics(fg_identity_analysis$model_2way)
result  # This will plot the diagnostics
```

### Functional group biomass
```{r}
#| label: fig-fg-biomass-diagnostics
#| echo: false
#| message: false
#| fig-height: 12

# Load the fg_biomass_analysis target
tar_load(fg_biomass_analysis)

# Check model diagnostics for the 2-way model
result <- check_model_diagnostics(fg_biomass_analysis)
result  # This will plot the diagnostics
``` 

## Part 2: single groups

### Functional group richness

#### Bryophytes
```{r}
#| label: fig-fg-richness-B-diagnostics
#| echo: false
#| message: false
#| fig-height: 12

# Load the fg_richness_focal_analysis target
tar_load(fg_richness_focal_analysis)

# Check model diagnostics for the 2-way model
result <- check_model_diagnostics(fg_richness_focal_analysis$bryophytes$model_2way)
result  # This will plot the diagnostics
```

#### Forbs

```{r}
#| label: fig-fg-richness-F-diagnostics
#| echo: false
#| message: false
#| fig-height: 12

# Load the fg_richness_focal_analysis target
tar_load(fg_richness_focal_analysis)

# Check model diagnostics for the 2-way model
result <- check_model_diagnostics(fg_richness_focal_analysis$forbs$model_2way)
result  # This will plot the diagnostics
```

#### Graminoids

```{r}
#| label: fig-fg-richness-G-diagnostics
#| echo: false
#| message: false
#| fig-height: 12

# Load the fg_richness_focal_analysis target
tar_load(fg_richness_focal_analysis)

# Check model diagnostics for the 2-way model
result <- check_model_diagnostics(fg_richness_focal_analysis$graminoids$model_2way)
result  # This will plot the diagnostics
```

### Functional group identity

#### bryophytes
```{r}
#| label: fig-fg-identity-B-diagnostics
#| echo: false
#| message: false
#| fig-height: 12

# Load the fg_identity_focal_analysis target
tar_load(fg_identity_focal_analysis)

# Check model diagnostics for the 2-way model
result <- check_model_diagnostics(fg_identity_focal_analysis$bryophytes$model_2way)
result  # This will plot the diagnostics
``` 
